version: '{build}'

environment:
  LATEX_BUILD_COMMAND:
    texify --pdf --tex-option="--tcx=UTF8" --tex-option="--enable-write18" --tex-option="--shell-escape" --tex-option="--interaction=nonstopmode" --batch
  LATEX_INPUT_DOC:
    report.tex
  FAIL_BUILD_ON_ERROR:
    yes

# cache miktex installation
# cache version = 8; change to cause cache invalidation
cache:
  - c:\miktex -> .\.latex.appveyor.yml

install:

  # fetch submodules
  - git submodule update --init --recursive

  # setup and install miktex if it was not restored from cache
  - set "PATH=%PATH%;c:\miktex\miktex\bin\x64"
  - cd .\appveyor-miktex-install
  - if not exist c:\miktex\miktex\bin\x64\texify.exe .\miktex-install.bat
  - cd ..

# build all configured submodules
build_script:
  - cp .\appveyor-latex-build\build.ps1 .\appveyor-latex-build.ps1
  - powershell -f .\appveyor-latex-build.ps1

